### ISSUE TITLE
JSON parser fails on Windows line endings

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/umbox#2]
I'm trying to run `umbox update` for the rail game on Windows:
```
UmBox error (6): json error: (box.json:9) unknown constant
```
The "constant" has the value of `"\r"` (0x0D).

**Comment by marekmaskarinec** [comment]
This should be fixed with the new update of json.um. Please verify and close.

**Comment by marekmaskarinec** [comment]
Yes

**Comment by vtereshkov** [comment]
Fix verified. Now I only observe #3 on `umbox update`.
