### ISSUE TITLE
`os.isdir()` fails on paths with trailing separators

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/umbox#3]
```
isdir("umbox\") = false
isdir("umbox") = true
```
This issue makes `umbox update` fail.

**Comment by marekmaskarinec** [comment]
This is interesting. Not sure why stat behaves this way. Is this possibly windows only behavior?

**Comment by marekmaskarinec** [comment]
I cannot recreate this in linux.

**Comment by vtereshkov** [comment]
I use this as a workaround:
```
fn isdir*(path: str): bool {
	if path[len(path) - 1] == '\\' {
		path = slice(path, 0, -1)		
	}
	return umc__isdir(path)
}
```

**Comment by vtereshkov** [comment]
@marekmaskarinec Would you like me to do some more testing on Windows?

**Comment by marekmaskarinec** [comment]
> I use this as a workaround:
> 
> ```
> fn isdir*(path: str): bool {
> 	if path[len(path) - 1] == '\\' {
> 		path = slice(path, 0, -1)		
> 	}
> 	return umc__isdir(path)
> }
> ```

This workaround could work. How does `umbox/` behave?

**Comment by vtereshkov** [comment]
@marekmaskarinec `umbox/` doesn't work either. 

But what has changed in the `isdir()` implementation? The function has been there for a long time, and without (?) any issues.

**Comment by marekmaskarinec** [comment]
The function didn't change. Maybe the issue only appeared after the error handling refactor.

**Comment by marekmaskarinec** [comment]
@vtereshkov I can implement your workaround. But I'm not sure where exactly this is failing. The only place in umbox that uses `isdir` shouldn't, in any case, have a trailing slash.

**Comment by vtereshkov** [comment]
@marekmaskarinec It's called from `mkdirp()`:
```
accum += parts[i] + str(filepath.fileseparator)
```

**Comment by marekmaskarinec** [comment]
I have implemented your workaround, it should be available from the downloads. By the way, could you please try showing me the results of `os.stat` for `umbox` and `umbox/` on your windows machine? Let's move this conversation to discord.

**Comment by vtereshkov** [comment]
For now, nothing has changed in the Windows installer.

**Comment by vtereshkov** [comment]
Fix verified.
